---

apiVersion: v1
kind: Namespace
metadata:
  name: hello-world-ns

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: hello-world-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: nginxdemos/hello:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: svc-helloworld
  namespace: hello-world-ns
spec:
  type: ClusterIP
  selector:
    app: hello-world
  ports:
    - protocol: TCP
      port: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing-helloworld
  namespace: hello-world-ns
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  labels:
    type: ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: svc-helloworld
            port:
              number: 80

---
